---
- name: Upload a lambda function to AWS
  hosts: localhost
  connection: local 
  tasks:
    - name: Create lambda function in AWS
      community.aws.lambda:
        name: 'Hello_World'
        state: present
        zip_file: 'files/helloworld.zip'
        runtime: 'python3.7'
        role: 'arn:aws:iam::165513844582:role/helloworlddemo'
        handler: 'lambda_function.lambda_handler'
        tags:
          app: 'test'
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"